// Ultrasonic sensor (HC-SR04) - using analog read on echo pin
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/2f8c6aaf-68a3-45b9-81b6-a8463f033b49 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  - No variables have been created, add cloud variables on the Thing Setup page
    to see them declared here

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include <WiFi.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <ArduinoOTA.h>
// #include "thingProperties.h"  // Temporarily disabled to fix compilation

WebServer server(80);

const int TRIG_PIN = 21;  // Trigger pin
const int ECHO_PIN = 22;  // Echo pin (will read analog)

// TCRT5000 IR Sensor 2
const int SENSOR2_A0 = 2;   // Analog output
const int SENSOR2_D0 = 16;  // Digital output

// Motor pin assignments (from user comments)
// m1: d32, d33
const int M1_PIN1 = 32;
const int M1_PIN2 = 33;

// m2: d25, d26
const int M2_PIN1 = 25;
const int M2_PIN2 = 26;

// m3: d19, d17
const int M3_PIN1 = 19;
const int M3_PIN2 = 23;

// m4: d18, d23
const int M4_PIN1 = 18;
const int M4_PIN2 = 17;

// m5: d27, d14
const int M5_PIN1 = 14;
const int M5_PIN2 = 27;

// m6: d12, d13
const int M6_PIN1 = 12;
const int M6_PIN2 = 13;

// forward declarations for motor control functions
void setMotor(int pin1, int pin2, bool forward, int speed);
void stopAllMotors();
void moveForward(int speed, unsigned long runMs);
void moveBackward(int speed, unsigned long runMs);
void turnLeft(int speed, unsigned long runMs);
void turnRight(int speed, unsigned long runMs);
void runMotor(int pin1, int pin2, int motorNum, bool forward, int speed, unsigned long runMs);

// Sensor functions
int readUltrasonicAnalog();

// helper sets all motors to same direction/speed
void setAllMotors(bool forward, int speed) {
  setMotor(M1_PIN1, M1_PIN2, forward, speed);
  setMotor(M2_PIN1, M2_PIN2, forward, speed);
  setMotor(M3_PIN1, M3_PIN2, forward, speed);
  setMotor(M4_PIN1, M4_PIN2, forward, speed);
  setMotor(M5_PIN1, M5_PIN2, forward, speed);
  setMotor(M6_PIN1, M6_PIN2, forward, speed);
}

// HTML for web interface
String htmlPage() {
  return R"rawliteral(
<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Lucas Control</title><style>
body { font-family: Arial, sans-serif; text-align: center; background-color: #f0f0f0; }
h3 { color: #333; }
button { width: 140px; height: 50px; margin: 6px; font-size: 16px; background-color: #4CAF50; color: white; border: none; border-radius: 5px; cursor: pointer; }
button:hover { background-color: #45a049; }
.control-section { margin: 20px; padding: 10px; border: 1px solid #ccc; border-radius: 10px; background-color: white; }
.sensor-display { font-size: 18px; margin: 10px; }
</style></head><body>
<h3>Lucas Motor Control</h3>
<div class="control-section">
<h4>All Motors</h4>
<div><button onclick=location.href='/all/forward'>All Forward</button><button onclick=location.href='/all/backward'>All Back</button><button onclick=location.href='/all/stop'>All Stop</button></div>
</div>
<div class="control-section">
<h4>Directional Control</h4>
<div><button onclick=location.href='/forward'>Forward</button><button onclick=location.href='/backward'>Backward</button><button onclick=location.href='/left'>Left</button><button onclick=location.href='/right'>Right</button><button onclick=location.href='/stop'>Stop</button></div>
</div>
<div class="control-section">
<h4>Individual Motors</h4>
<div> M1 <button onclick=location.href='/m1/forward'>F</button> <button onclick=location.href='/m1/backward'>B</button></div>
<div> M2 <button onclick=location.href='/m2/forward'>F</button> <button onclick=location.href='/m2/backward'>B</button></div>
<div> M3 <button onclick=location.href='/m3/forward'>F</button> <button onclick=location.href='/m3/backward'>B</button></div>
<div> M4 <button onclick=location.href='/m4/forward'>F</button> <button onclick=location.href='/m4/backward'>B</button></div>
<div> M5 <button onclick=location.href='/m5/forward'>F</button> <button onclick=location.href='/m5/backward'>B</button></div>
<div> M6 <button onclick=location.href='/m6/forward'>F</button> <button onclick=location.href='/m6/backward'>B</button></div>
</div>
<div class="control-section">
<h4>All Motors</h4>
<div><button onclick=location.href='/all/forward'>All Forward</button><button onclick=location.href='/all/backward'>All Back</button><button onclick=location.href='/all/stop'>All Stop</button></div>
</div>
<div class="control-section">
<h4>Directional Control</h4>
<div><button onclick=location.href='/forward'>Forward</button><button onclick=location.href='/backward'>Backward</button><button onclick=location.href='/left'>Left</button><button onclick=location.href='/right'>Right</button><button onclick=location.href='/stop'>Stop</button></div>
</div>
<div class="control-section">
<h4>Sensor Readings</h4>
<div class="sensor-display">Ultrasonic Distance: <span id="ultrasonic">--</span> cm</div>
<div class="sensor-display">IR Analog: <span id="irAnalog">--</span></div>
<div class="sensor-display">IR Digital: <span id="irDigital">--</span></div>
</div>
<p>mDNS: <b>lucas.local</b></p>
<script>
function updateSensors() {
  fetch('/sensors')
    .then(response => response.json())
    .then(data => {
      document.getElementById('ultrasonic').textContent = data.ultrasonic;
      document.getElementById('irAnalog').textContent = data.irAnalog;
      document.getElementById('irDigital').textContent = data.irDigital;
    })
    .catch(error => console.error('Error fetching sensors:', error));
}
setInterval(updateSensors, 1000);
updateSensors();
</script>
</body></html>
)rawliteral";
}

// M5 control variables
unsigned long m5LastSwitchTime = 0;
const unsigned long M5_INTERVAL = 3000; // 3 seconds
bool m5Forward = true; // Track direction for all motors

// Non-blocking motor timing variables
struct MotorState {
  bool active = false;
  unsigned long startTime = 0;
  unsigned long duration = 0;
  int pin1 = 0, pin2 = 0;
  bool forward = false;
  int speed = 0;
};
MotorState currentMotor = {false, 0, 0, 0, 0, false, 0};

void setup(){
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  // initProperties();  // Temporarily disabled

  // Connect to Arduino IoT Cloud (handles WiFi automatically)
  // ArduinoCloud.begin(ArduinoIoTPreferredConnection);  // Temporarily disabled
  
  // Manual WiFi connection
  WiFi.begin("potato", "potato123");
  Serial.print("Connecting to WiFi...");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println(" Connected!");
  Serial.print("IP: "); Serial.println(WiFi.localIP());
  
  // Configure ultrasonic pins
  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);  // Read ECHO_PIN as analog

  // Configure Sensor 2 D0 pin as digital input
  pinMode(SENSOR2_D0, INPUT);

  Serial.println("Ultrasonic + TCRT5000 IR Sensor Test");
  Serial.println("====================================");
  Serial.print("Ultrasonic Trig -> "); Serial.print(TRIG_PIN); Serial.print(", Echo -> "); Serial.println(ECHO_PIN);
  Serial.print("Sensor2 A0 -> "); Serial.print(SENSOR2_A0); Serial.print(", D0 -> "); Serial.println(SENSOR2_D0);
  Serial.println();

  // Configure motor pins as outputs
  pinMode(M1_PIN1, OUTPUT); pinMode(M1_PIN2, OUTPUT);
  pinMode(M2_PIN1, OUTPUT); pinMode(M2_PIN2, OUTPUT);
  pinMode(M3_PIN1, OUTPUT); pinMode(M3_PIN2, OUTPUT);
  pinMode(M4_PIN1, OUTPUT); pinMode(M4_PIN2, OUTPUT);
  pinMode(M5_PIN1, OUTPUT); pinMode(M5_PIN2, OUTPUT);
  pinMode(M6_PIN1, OUTPUT); pinMode(M6_PIN2, OUTPUT);
  pinMode(0, INPUT_PULLUP); // user button

  // Turn all motors off
  digitalWrite(M1_PIN1, LOW); digitalWrite(M1_PIN2, LOW);
  digitalWrite(M2_PIN1, LOW); digitalWrite(M2_PIN2, LOW);
  digitalWrite(M3_PIN1, LOW); digitalWrite(M3_PIN2, LOW);
  digitalWrite(M4_PIN1, LOW); digitalWrite(M4_PIN2, LOW);
  digitalWrite(M5_PIN1, LOW); digitalWrite(M5_PIN2, LOW);
  digitalWrite(M6_PIN1, LOW); digitalWrite(M6_PIN2, LOW);

  // Arduino IoT Cloud handles WiFi connection automatically
  Serial.println("Connecting to Arduino IoT Cloud...");
  delay(2000); // Give it time to connect
  
  // Initialize OTA
  ArduinoOTA.setHostname("Lucas-ESP32");
  ArduinoOTA.begin();
  Serial.println("OTA initialized");

  // Start mDNS
  if (MDNS.begin("lucas")) {
    MDNS.addService("http", "tcp", 80);
    Serial.println("mDNS responder started as lucas.local");
  } else {
    Serial.println("Failed to start mDNS");
  }

  // Web server endpoints
  server.on("/", [](){ server.send(200, "text/html", htmlPage()); });
  server.on("/sensors", [](){
    int ultrasonic = readUltrasonicAnalog();
    int irAnalog = analogRead(SENSOR2_A0);
    int irDigital = digitalRead(SENSOR2_D0);
    String json = "{";
    json += "\"ultrasonic\":" + String(ultrasonic) + ",";
    json += "\"irAnalog\":" + String(irAnalog) + ",";
    json += "\"irDigital\":" + String(irDigital);
    json += "}";
    server.send(200, "application/json", json);
  });
  server.on("/all/forward", [](){ setAllMotors(true, 200); server.sendHeader("Location","/"); server.send(302,"text/plain",""); });
  server.on("/all/backward", [](){ setAllMotors(false, 200); server.sendHeader("Location","/"); server.send(302,"text/plain",""); });
  server.on("/all/stop", [](){ stopAllMotors(); server.sendHeader("Location","/"); server.send(302,"text/plain",""); });

  server.on("/forward", [](){ scheduleMotorSequence(M4_PIN1, M4_PIN2, M5_PIN1, M5_PIN2, M6_PIN1, M6_PIN2, M3_PIN1, M3_PIN2, true, 200, 2000); server.sendHeader("Location","/"); server.send(302,"text/plain",""); });
  server.on("/backward", [](){ scheduleMotorSequence(M4_PIN1, M4_PIN2, M5_PIN1, M5_PIN2, M6_PIN1, M6_PIN2, M3_PIN1, M3_PIN2, false, 200, 2000); server.sendHeader("Location","/"); server.send(302,"text/plain",""); });
  server.on("/left", [](){ turnLeftNonBlocking(200, 2000); server.sendHeader("Location","/"); server.send(302,"text/plain",""); });
  server.on("/right", [](){ turnRightNonBlocking(200, 2000); server.sendHeader("Location","/"); server.send(302,"text/plain",""); });
  server.on("/stop", [](){ stopAllMotors(); server.sendHeader("Location","/"); server.send(302,"text/plain",""); });

  // Individual motor endpoints
  server.onNotFound([](){
    String uri = server.uri();
    // support /mX/forward and /mX/backward
    for (int i=1;i<=6;i++){
      String fwd = "/m" + String(i) + "/forward";
      String bwd = "/m" + String(i) + "/backward";
      if (uri == fwd) {
        // map motor i to pins
        if (i==1) scheduleMotor(M1_PIN1,M1_PIN2,i,true,200,2000);
        if (i==2) scheduleMotor(M2_PIN1,M2_PIN2,i,true,200,2000);
        if (i==3) scheduleMotor(M3_PIN1,M3_PIN2,i,true,200,2000);
        if (i==4) scheduleMotor(M4_PIN1,M4_PIN2,i,true,200,2000);
        if (i==5) scheduleMotor(M5_PIN1,M5_PIN2,i,true,200,2000);
        if (i==6) scheduleMotor(M6_PIN1,M6_PIN2,i,true,200,2000);
        server.sendHeader("Location","/"); server.send(302,"text/plain",""); return;
      }
      if (uri == bwd) {
        if (i==1) scheduleMotor(M1_PIN1,M1_PIN2,i,false,200,2000);
        if (i==2) scheduleMotor(M2_PIN1,M2_PIN2,i,false,200,2000);
        if (i==3) scheduleMotor(M3_PIN1,M3_PIN2,i,false,200,2000);
        if (i==4) scheduleMotor(M4_PIN1,M4_PIN2,i,false,200,2000);
        if (i==5) scheduleMotor(M5_PIN1,M5_PIN2,i,false,200,2000);
        if (i==6) scheduleMotor(M6_PIN1,M6_PIN2,i,false,200,2000);
        server.sendHeader("Location","/"); server.send(302,"text/plain",""); return;
      }
    }
    server.send(404, "text/plain", "Not found");
  });

  server.begin();
  Serial.println("HTTP server started");
  Serial.println("\n=== LUCAS ROBOT CONTROL ===");
  Serial.println("Web interface: http://lucas.local");
  Serial.println("Serial commands:");
  Serial.println("  F/B/L/R/S - Directional control");
  Serial.println("  AF/AB/AS - All motors control"); 
  Serial.println("  M1F/M1B to M6F/M6B - Individual motors");
  Serial.println("Send commands via Serial Monitor");
}
}

// Function to read ultrasonic sensor via analog input
int readUltrasonicAnalog() {
    digitalWrite(TRIG_PIN, LOW);
  delayMicroseconds(2);
  digitalWrite(TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(TRIG_PIN, LOW);

  long duration = pulseIn(ECHO_PIN, HIGH, 30000); // timeout after 30ms (~5m max)
  
  // Calculate distance: speed of sound is ~343 m/s (0.0343 cm/µs)
  // distance = (duration / 2) * 0.0343 cm
  float distance = (duration / 2.0) * 0.0343;

  return distance;

}

// Function to drive all 6 motors with alternating direction every 3 seconds
void driveAllMotors(int speed) {
  unsigned long currentTime = millis();
  
  // Check if 3 seconds have passed
  if (currentTime - m5LastSwitchTime >= M5_INTERVAL) {
    m5LastSwitchTime = currentTime;
    m5Forward = !m5Forward; // Toggle direction for all motors
  }
  
  // Fixed speed for all motors
  int motorSpeed = 200;
  
  if (m5Forward) {
    // All motors forward: PIN1 HIGH, PIN2 LOW
    analogWrite(M1_PIN1, motorSpeed); digitalWrite(M1_PIN2, LOW);
    analogWrite(M2_PIN1, motorSpeed); digitalWrite(M2_PIN2, LOW);
    analogWrite(M3_PIN1, motorSpeed); digitalWrite(M3_PIN2, LOW);
    analogWrite(M4_PIN1, motorSpeed); digitalWrite(M4_PIN2, LOW);
    analogWrite(M5_PIN1, motorSpeed); digitalWrite(M5_PIN2, LOW);
    analogWrite(M6_PIN1, motorSpeed); digitalWrite(M6_PIN2, LOW);
  } else {
    // All motors backward: PIN1 LOW, PIN2 HIGH
    digitalWrite(M1_PIN1, LOW); analogWrite(M1_PIN2, motorSpeed);
    digitalWrite(M2_PIN1, LOW); analogWrite(M2_PIN2, motorSpeed);
    digitalWrite(M3_PIN1, LOW); analogWrite(M3_PIN2, motorSpeed);
    digitalWrite(M4_PIN1, LOW); analogWrite(M4_PIN2, motorSpeed);
    digitalWrite(M5_PIN1, LOW); analogWrite(M5_PIN2, motorSpeed);
    digitalWrite(M6_PIN1, LOW); analogWrite(M6_PIN2, motorSpeed);
  }
  delay(300);
}

// Function to alternate M5 direction every 3 seconds
void alternateM5() {
  // Direction alternation is now handled in driveAllMotors()
}

// Set motor direction without delay (for simultaneous control)
void setMotor(int pin1, int pin2, bool forward, int speed) {
  if (forward) {
    digitalWrite(pin1, HIGH); digitalWrite(pin2, LOW);
  } else {
    digitalWrite(pin1, LOW); digitalWrite(pin2, HIGH);
  }
}

void stopAllMotors() {
  digitalWrite(M1_PIN1, LOW); digitalWrite(M1_PIN2, LOW);
  digitalWrite(M2_PIN1, LOW); digitalWrite(M2_PIN2, LOW);
  digitalWrite(M3_PIN1, LOW); digitalWrite(M3_PIN2, LOW);
  digitalWrite(M4_PIN1, LOW); digitalWrite(M4_PIN2, LOW);
  digitalWrite(M5_PIN1, LOW); digitalWrite(M5_PIN2, LOW);
  digitalWrite(M6_PIN1, LOW); digitalWrite(M6_PIN2, LOW);
}

// Non-blocking motor scheduling
void scheduleMotor(int pin1, int pin2, int motorNum, bool forward, int speed, unsigned long runMs) {
  Serial.print("Scheduled Motor "); Serial.print(motorNum); Serial.print(" -> ");
  Serial.println(forward ? "Forward" : "Backward");
  // Start motor immediately
  if (forward) {
    analogWrite(pin1, speed); digitalWrite(pin2, LOW);
  } else {
    digitalWrite(pin1, LOW); analogWrite(pin2, speed);
  }
  // Schedule stop via millis
  currentMotor = {true, millis(), runMs, pin1, pin2, forward, speed};
}

void scheduleMotorSequence(int p1a, int p2a, int p1b, int p2b, int p1c, int p2c, int p1d, int p2d, bool fwd, int spd, unsigned long ms) {
  Serial.println(fwd ? "Scheduled: Forward" : "Scheduled: Backward");
  analogWrite(p1a, spd); digitalWrite(p2a, LOW);
  analogWrite(p1b, spd); digitalWrite(p2b, LOW);
  analogWrite(p1c, spd); digitalWrite(p2c, LOW);
  analogWrite(p1d, spd); digitalWrite(p2d, LOW);
  currentMotor = {true, millis(), ms, 0, 0, fwd, spd};
}

void turnLeftNonBlocking(int speed, unsigned long runMs) {
  Serial.println("Scheduled: turnLeft");
  setMotor(M5_PIN1, M5_PIN2, false, speed);
  setMotor(M6_PIN1, M6_PIN2, true, speed);
  setMotor(M4_PIN1, M4_PIN2, false, speed);
  setMotor(M3_PIN1, M3_PIN2, true, speed);
  currentMotor = {true, millis(), runMs, 0, 0, false, speed};
}

void turnRightNonBlocking(int speed, unsigned long runMs) {
  Serial.println("Scheduled: turnRight");
  setMotor(M6_PIN1, M6_PIN2, true, speed);
  setMotor(M5_PIN1, M5_PIN2, false, speed);
  setMotor(M4_PIN1, M4_PIN2, true, speed);
  setMotor(M3_PIN1, M3_PIN2, false, speed);
  currentMotor = {true, millis(), runMs, 0, 0, true, speed};
}

// Keep old functions for compatibility
void moveForward(int speed, unsigned long runMs) {
  Serial.println("Action: moveForward (m4,m5,m6,m3) -> Forward");
  setMotor(M4_PIN1, M4_PIN2, true, speed);
  setMotor(M5_PIN1, M5_PIN2, true, speed);
  setMotor(M6_PIN1, M6_PIN2, true, speed);
  setMotor(M3_PIN1, M3_PIN2, true, speed);
}

void moveBackward(int speed, unsigned long runMs) {
  Serial.println("Action: moveBackward (m4,m5,m6,m3) -> Backward");
  setMotor(M4_PIN1, M4_PIN2, false, speed);
  setMotor(M5_PIN1, M5_PIN2, false, speed);
  setMotor(M6_PIN1, M6_PIN2, false, speed);
  setMotor(M3_PIN1, M3_PIN2, false, speed);
}

void turnLeft(int speed, unsigned long runMs) {
  Serial.println("Action: turnLeft -> M6 forward, M5 backward, M3 forward, M4 backward");
  setMotor(M5_PIN1, M5_PIN2, false, speed);
  setMotor(M6_PIN1, M6_PIN2, true, speed);
  setMotor(M4_PIN1, M4_PIN2, false, speed);
  setMotor(M3_PIN1, M3_PIN2, true, speed);
}

void turnRight(int speed, unsigned long runMs) {
  Serial.println("Action: turnRight -> opposite of turnLeft");
  setMotor(M6_PIN1, M6_PIN2, true, speed);
  setMotor(M5_PIN1, M5_PIN2, false, speed);
  setMotor(M4_PIN1, M4_PIN2, true, speed);
  setMotor(M3_PIN1, M3_PIN2, false, speed);
}
// // Motor 3 F
// Motor 4 E
// Motor 5 B
// // Motor 6 A
// Check if motor timing has elapsed and stop if needed
void updateMotorTiming() {
  if (currentMotor.active && (millis() - currentMotor.startTime >= currentMotor.duration)) {
    stopAllMotors();
    currentMotor.active = false;
    Serial.println("Motor runtime complete");
  }
}

// Handle serial commands for motor control
void handleSerialCommand(String cmd) {
  Serial.print("Serial Command: ");
  Serial.println(cmd);
  
  if (cmd == "FORWARD" || cmd == "F") {
    Serial.println("Moving Forward");
    scheduleMotorSequence(M4_PIN1, M4_PIN2, M5_PIN1, M5_PIN2, M6_PIN1, M6_PIN2, M3_PIN1, M3_PIN2, true, 200, 2000);
  }
  else if (cmd == "BACKWARD" || cmd == "B") {
    Serial.println("Moving Backward");
    scheduleMotorSequence(M4_PIN1, M4_PIN2, M5_PIN1, M5_PIN2, M6_PIN1, M6_PIN2, M3_PIN1, M3_PIN2, false, 200, 2000);
  }
  else if (cmd == "LEFT" || cmd == "L") {
    Serial.println("Turning Left");
    turnLeftNonBlocking(200, 2000);
  }
  else if (cmd == "RIGHT" || cmd == "R") {
    Serial.println("Turning Right");
    turnRightNonBlocking(200, 2000);
  }
  else if (cmd == "STOP" || cmd == "S") {
    Serial.println("Stopping All Motors");
    stopAllMotors();
  }
  else if (cmd == "ALL_FORWARD" || cmd == "AF") {
    Serial.println("All Motors Forward");
    setAllMotors(true, 200);
  }
  else if (cmd == "ALL_BACKWARD" || cmd == "AB") {
    Serial.println("All Motors Backward");
    setAllMotors(false, 200);
  }
  else if (cmd == "ALL_STOP" || cmd == "AS") {
    Serial.println("All Motors Stop");
    stopAllMotors();
  }
  else if (cmd.startsWith("M")) {
    // Individual motor control: M1F, M2B, etc.
    int motorNum = cmd.substring(1, 2).toInt();
    String direction = cmd.substring(2);
    bool forward = (direction == "F");
    
    if (motorNum >= 1 && motorNum <= 6) {
      Serial.print("Motor "); Serial.print(motorNum); Serial.println(forward ? " Forward" : " Backward");
      if (motorNum == 1) scheduleMotor(M1_PIN1, M1_PIN2, motorNum, forward, 200, 2000);
      if (motorNum == 2) scheduleMotor(M2_PIN1, M2_PIN2, motorNum, forward, 200, 2000);
      if (motorNum == 3) scheduleMotor(M3_PIN1, M3_PIN2, motorNum, forward, 200, 2000);
      if (motorNum == 4) scheduleMotor(M4_PIN1, M4_PIN2, motorNum, forward, 200, 2000);
      if (motorNum == 5) scheduleMotor(M5_PIN1, M5_PIN2, motorNum, forward, 200, 2000);
      if (motorNum == 6) scheduleMotor(M6_PIN1, M6_PIN2, motorNum, forward, 200, 2000);
    }
  }
  else {
    Serial.println("Unknown command. Available commands:");
    Serial.println("F/B/L/R/S - Directional control");
    Serial.println("AF/AB/AS - All motors control");
    Serial.println("M1F/M1B to M6F/M6B - Individual motors");
  }
}

void loop() {
  // ArduinoCloud.update();  // Temporarily disabled
  ArduinoOTA.handle();
  server.handleClient();
  updateMotorTiming();  // Non-blocking check for motor timeout
  
  // Handle serial commands
  if (Serial.available()) {
    String command = Serial.readStringUntil('\n');
    command.trim();
    if (command.length() > 0) {
      handleSerialCommand(command);
    }
  }
  
  delay(5);  // Reduced from 10ms for better responsiveness
}